package Swing;

// Demonstrate check boxes.

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class CBDemo implements ItemListener {

    JLabel jlabSelected, jlabChanged;
    JCheckBox jcbAlpha, jcbBeta, jcbGamma;

    CBDemo() {
        // Create a new JFrame container.
        JFrame jfrm = new JFrame("Demonstrate Check Boxes");

        // Specify FlowLayout for the layout manager.
        jfrm.setLayout(new FlowLayout());

        // Give frame an initial size.
        jfrm.setSize(260, 120);

        // Terminate program when user closes application.
        jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Create empty labels.
        jlabSelected = new JLabel("");
        jlabChanged = new JLabel("");

        // Make check boxes.
        jcbAlpha = new JCheckBox("Alpha");
        jcbBeta = new JCheckBox("Beta");
        jcbGamma = new JCheckBox("Gamma");

        // Events generated by check boxes are handled in common by
        // itemStateChanged() method implemented by CBDemo.
        jcbAlpha.addItemListener(this);
        jcbBeta.addItemListener(this);
        jcbGamma.addItemListener(this);

        // Add check boxes and labels to content pane.
        jfrm.add(jcbAlpha);
        jfrm.add(jcbBeta);
        jfrm.add(jcbGamma);
        jfrm.add(jlabChanged);
        jfrm.add(jlabSelected);

        // Display frame.
        jfrm.setVisible(true);
    }

    // This is the handler for check boxes.
    public void itemStateChanged(ItemEvent ie) {
        String str = "";

        // Obtain reference to check box that caused the event.
        JCheckBox cb = (JCheckBox) ie.getItem();

        // Report what check box has changed.
        if(cb.isSelected())
            jlabChanged.setText(cb.getText() + " was just selected");
        else
            jlabChanged.setText(cb.getText() + " was just cleared");

        // Report all selected boxes.
        if(jcbAlpha.isSelected())
            str += "Alpha ";
        if(jcbBeta.isSelected())
            str += "Beta ";
        if(jcbGamma.isSelected())
            str += "Gamma";

        jlabSelected.setText("Selected check boxes: " + str);
    }

    public static void main(String[] args) {
        // Create frame on event dispatching thread.
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CBDemo();
            }
        });
    }
}
